version: 0.2

phases:
    pre_build:
        commands:
            - 'echo `date`: Installing package for testing...'
            - 'python setup.py install'
            - 'echo `date`: Running unit tests...'
            - 'py.test test'
            - 'echo `date`: Validating CFN Lambda Template'
            - 'aws cloudformation validate-template --template-body file://infra/cloudformation/ebcf-alexa-lambda.template.yml'
    build:
        commands:
            - 'echo `date`: Building Python Package'
            - >
                python setup.py install
                --single-version-externally-managed
                --root=archive-build-root
                --install-base=
                --install-purelib=
                --install-platlib=
                --install-scripts=
                --install-data=
                --install-platbase=
                --install-headers=
            - 'echo `date`: Installing dependencies'
            - 'pip install -r requirements.txt -t archive-build-root'
            - 'echo `date`: Copying Lambda CFN Template'
            - 'cp -v infra/cloudformation/ebcf-alexa-lambda.template.yml archive-build-root/'
            - 'cp -v infra/cloudformation/ebcf-alexa-lambda.config.*.json archive-build-root/'
artifacts:
    files:
        - '**/*'
    base-directory: archive-build-root
