version: 0.2

phases:
    pre_build:
        commands:
            - echo Running unit tests on `date`
            - python3 setup.py test
            - echo Validating lambda CFN template on `date`
            - infra/validate-cfn infra/cloudformation/ebcf-alexa-lambda.template.yml
    build:
        commands:
            - echo Starting build on `date`
            - >
                python3 setup.py install
                --single-version-externally-managed
                --root=archive-build-root
                --install-base=
                --install-purelib=
                --install-platlib=
                --install-scripts=
                --install-data=
                --install-platbase=
                --install-headers=
            - pip install -r requirements.txt -t archive-build-root
            - cp -v infra/cloudformation/ebcf-alexa-lambda.template.yml archive-build-root/
artifacts:
    files:
        - '**/*'
    base-directory: archive-build-root
