version: 0.2

phases:
    install:
        commands:
            - echo `date`: Installing python dependencies
            - pip install -r infra/requirements.txt
            - pip install -r requirements.txt
    pre_build:
        commands:
            - echo `date`: Running unit tests...
            - py.test test
            - echo `date`: Validating CFN Lambda Template
            - infra/validate-cfn infra/cloudformation/ebcf-alexa-lambda.template.yml
    build:
        commands:
            - echo Starting build on `date`
            - >
                python3 setup.py install
                --single-version-externally-managed
                --root=archive-build-root
                --install-base=
                --install-purelib=
                --install-platlib=
                --install-scripts=
                --install-data=
                --install-platbase=
                --install-headers=
            - pip install -r requirements.txt -t archive-build-root
            - cp -v infra/cloudformation/ebcf-alexa-lambda.template.yml archive-build-root/
artifacts:
    files:
        - '**/*'
    base-directory: archive-build-root
