version: 0.2

phases:
    pre_build:
        commands:
            - echo Running unit tests on `date`
            - python3 setup.py test
    build:
        commands:
            - echo Starting build on `date`
            - >
                python3 setup.py install
                --single-version-externally-managed
                --root=archive-build-root
                --install-base=
                --install-purelib=
                --install-scripts=
                --install-data=
                --install-platbase=
                --install-headers=
            - pip install -r requirements.txt -t archive-build-root
artifacts:
    files:
        - '**/*'
    base-directory: archive-build-root
